apiVersion: v1
kind: Pod
metadata:
  name: test2
  labels:
    app: test
  annotations:
    diskIO: "10"
spec:
  schedulerName: yoda-scheduler
  containers:
    - image: k765171999/iotest:v1.0.0
      name: iotest-v1
      args: ["10240", "1"]
      resources:
        requests:
          cpu: 100m
          memory: 400Mi

